<h1 style="text-align:center">Introduction to Python</h1>
<hr/>

# 1. Basic Operations with Python

### Writing comments

Comments are written in Python using # sign

In [14]:
# This is a Python comment

### Printing Values
When working with Python using Jupyter Notebook, the result of the final line of code will be printed by default. If any intermediate value is required to be printed, the print() function can be used.

In [15]:
print('This will be printed below')

This will be printed below


### Assigning Values
Value assignment is done using the = symbol.

In [20]:
a = 5
print('The value of a is', a)

The value of a is 5


### Addition, Subtraction, Multiplication and Division
Addition and subtraction is done using the standard mathematical operators.

In [19]:
a = 10
b = 6
c = a + b
print('c =',c)
d = a - b
print('d =',d)

c = 16
d = 4


Multiplication is done using * symbol.

In [21]:
e = a * b
print('e = ',e)

e =  30


Division can be standard division using / symbol, modulus using % symbol or ...

In [26]:
f = b / a
print('f =',f)

g = b % a
print('g =',g)

f = 1.2
g = 1


# 2. Important Python Functions

*range()*

Used to generate values in iterations.

In [30]:
for i in range(1,5):
    print(i)

1
2
3
4


*round()*

Used to round numbers.

In [31]:
round(5.215235869,2)

5.22

# 3. Python Loops and Conditionals

# 2. Working with Numpy Ndarray

In [1]:
# Importing required libraries
import numpy as np

Python array index starts at zero.

Creating empty array:

In [13]:
A = np.empty((2,3))
A.shape

(2, 3)

Creating array of zeros:

In [32]:
A = np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

Creating array of ones:

In [37]:
A = np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

Creating array of same values:

In [35]:
A = np.full((2,3),5)
A

array([[5, 5, 5],
       [5, 5, 5]])

### Rounding all values

For rounding all the values of a numpy array around() method can be used.

In [39]:
A = np.full((3,3), 5.263645625)
A

array([[5.26364562, 5.26364562, 5.26364562],
       [5.26364562, 5.26364562, 5.26364562],
       [5.26364562, 5.26364562, 5.26364562]])

In [40]:
np.around(A,2)

array([[5.26, 5.26, 5.26],
       [5.26, 5.26, 5.26],
       [5.26, 5.26, 5.26]])

# 2. Working with Pandas Data Frame